import Head from 'next/head';
import React, { FunctionComponent } from 'react';
import countriesApi from '../../src/api/countries';
import { Country } from '../../src/models/Country';
import CountryPageComponent from '../../src/pages/country/Country';

interface CountryPageProps {
  country: Country;
}

const CountryPage: FunctionComponent<CountryPageProps> = ({ country }) => {

  return (
    <div>
      <Head>
        <title>Country Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <CountryPageComponent country={ country } />
      </main>
    </div>
  )
}

export const getStaticPaths = async () => {

  const countries: Country[] = await countriesApi.getAll();
  const paths: { params: { uid: string; }; }[] = countries.map(country => ( { params: { uid: country.alpha3Code } } ) );

  return {
    paths,
    fallback: true,
  }
};

export const getStaticProps = async (props: { params: { uid: string | any[]; }; }) => {
  const { params } = props;

  const country = await countriesApi.getByCountryCode(params?.uid as string)

  return {
    props: {
      country: country
    },
  };
};


export default CountryPage;
