import Head from 'next/head';
import { GetStaticProps } from 'next';
import React, { FunctionComponent } from 'react';
import countriesApi from '../../src/api/countries';
import { Country } from '../../src/models/Country';
import CountryPageComponent from '../../src/pages/country/Country';

interface CountryPageProps {
  country: Country;
}

const CountryPage: FunctionComponent<CountryPageProps> = ({ country }) => {

  return (
    <div>
      <Head>
        <title>Country Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <CountryPageComponent country={ country } />
      </main>
    </div>
  )
}

export const getStaticPaths = async () => {
  return {
    paths: [
      '/country/[uid]',
      { params: { uid: 'some-uid' } },
    ],
    fallback: true,
  }
};

export const getStaticProps = async (props: { params: { uid: string | any[]; }; }) => {
  const { params } = props;

  const country = await countriesApi.getByCountryCode(params?.uid as string)
  console.log("THE COUNTRY", country)

  return {
    props: {
      country: country
    },
  };
};


export default CountryPage;
