import Head from "next/head";
import React from "react";

const Home: () => JSX.Element = () => {
  return (
    <div>
      <Head>
        <title>Next JS Countries App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}


export default Home;