import Head from 'next/head'
import Image from 'next/image'
import { FunctionComponent } from 'react'
import countriesApi from '../../src/api/countries'
import { Country } from '../../src/models/Country'

interface CountriesPageProps {
  countries: Country[];
  toggleTheme: () => void;
}

const CountriesPage: FunctionComponent<CountriesPageProps> = ({ countries, toggleTheme }) => {
  console.log('countries', countries[0])

  return (
    <div>
      <Head>
        <title>Next JS Countries App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
       Countries Page
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getStaticProps = async () => {
  
  const allCountries = await countriesApi.getAll()
  
  return {
    props: {
      countries: allCountries,
    },
  };
};


export default CountriesPage;
