import Head from 'next/head'
import React, { FunctionComponent } from 'react'
import countriesApi from '../../src/api/countries'
import { Country } from '../../src/models/Country'
import CountriesPageComponent from '../../src/pages/countries/Countries'

interface CountriesPageProps {
  countries: Country[];
}

const CountriesPage: FunctionComponent<CountriesPageProps> = ({ countries }) => {

  return (
    <div>
      <Head>
        <title>Next JS Countries App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <CountriesPageComponent countries={ countries } />
      </main>
    </div>
  )
}

export const getStaticProps = async () => {
  
  const allCountries = await countriesApi.getAll()
  
  return {
    props: {
      countries: allCountries,
    },
  };
};


export default CountriesPage;
