name: Verify

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          registry-url: https://npm.pkg.github.com

      - name: Install dependencies
        run: npm ci

      - name: Run Linters
        run: npm run lint

      
      # - name: Run Unit Tests
      #   run: npm run test

# Cypress server to be configured
# Cypress tests to be run
# Make sure your split test suite on all runners, so tests are running in parallel

      # - name: Run Integration Tests
      #   run: npm run cypress:headless-ci

# We could also integrate Chromatic for visual regression testing & SB deployment
# https://www.chromatic.com/

